/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionMenu: typeof import('./src/components/ActionMenu.vue')['default']
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    BackupsDialog: typeof import('./src/components/BackupsDialog.vue')['default']
    BarTimeline: typeof import('./src/components/BarTimeline.vue')['default']
    BenchCommandDialog: typeof import('./src/components/BenchCommandDialog.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    HealthPanel: typeof import('./src/components/HealthPanel.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    InstallDialog: typeof import('./src/components/InstallDialog.vue')['default']
    JobDock: typeof import('./src/components/JobDock.vue')['default']
    JobSteps: typeof import('./src/components/JobSteps.vue')['default']
    LogsDialog: typeof import('./src/components/LogsDialog.vue')['default']
    OutcomeMark: typeof import('./src/components/OutcomeMark.vue')['default']
    RankBars: typeof import('./src/components/RankBars.vue')['default']
    RestoreDialog: typeof import('./src/components/RestoreDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchSelect: typeof import('./src/components/SearchSelect.vue')['default']
    SiteConfigDialog: typeof import('./src/components/SiteConfigDialog.vue')['default']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
    SslDialog: typeof import('./src/components/SslDialog.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
  }
}
