/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    BarTimeline: typeof import('./src/components/BarTimeline.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    InstallDialog: typeof import('./src/components/InstallDialog.vue')['default']
    JobDock: typeof import('./src/components/JobDock.vue')['default']
    OutcomeMark: typeof import('./src/components/OutcomeMark.vue')['default']
    RankBars: typeof import('./src/components/RankBars.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
  }
}
